<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<?php
/** @var $block \Magento\Downloadable\Block\Checkout\Cart\Item\Renderer */
if ($_options = $block->getOptionList()) : ?>
    <?php foreach ($_options as $_option) : ?>
        <?php $formattedOptionValue = $block->getFormatedOptionValue($_option) ?>
        <dl>
            <dt><b><?= $block->escapeHtml($_option['label']) ?>:</b></dt>
            <dd>
                <?php if (isset($formattedOptionValue['full_view'])) : ?>
                    <?= $block->escapeHtml($formattedOptionValue['full_view']) ?>
                <?php else : ?>
                    <?= $block->escapeHtml($formattedOptionValue['value']) ?>
                <?php endif; ?>
            </dd>
        </dl>
    <?php endforeach; ?>
<?php endif; ?>
